### PR TITLE
unsafeInstanceOf Quality, closes #155

### LINKED ISSUE #155: InstanceOf and raw types
In theory Confidence should be able to support something like hamcrest/JavaHamcrest#388, like this:

```java
        Map<String, Object> actual = Map.of(
            "k1", Map.of(
                "k11", "v11",
                "k12", "v12"),
            "k2", List.of("v21", "v22"),
            "k3", "v3"
        );

        assertThat(actual, Core.<Map<String, Object>>allOf(
                containsEntry("k1", instanceOf(Map.class, allOf(
                    containsEntry("k11", "v11"),
                    containsEntry("k12", "v12"))
                )),
                containsEntry("k2", instanceOf(Iterable.class, iterates("v21", "v22"))),
                containsEntry("k3", instanceOf(String.class, equalTo("v3")))
            )
        );
```

The problem, however, is, that `instanceOf` does not play well with raw types but we can't pass a `Class` instance of a generic type (because there is no such thing). The problem is that a generic `Map` type is *never* a supertype of a raw type.

Changing the `InstanceOf` constructor from
```
    public <V extends T> InstanceOf(Class<V> expectation, Quality<? super V> delegate)
```
to 
```
    public <V extends T, Q extends V> InstanceOf(Class<V> expectation, Quality<? super Q> delegate)
```
indeed fixes the issue because you can now pass a `Quality` for any subtype of `V` but that's not really type safe anymore because there is no guarantee that the tested instance is indeed a `Q` .

This would compile now (it doesn't without this change) but the test would fail with a `ClassCastException`
```
    static class C1 {
        int foo() {
            return 1;
        }
    }
    
    static class C2 extends C1 {
        int bar() {
            return 2;
        }
    }
    
    @Test
    void instanceOfTest()
    {
        Object o = new C1();
        assertThat(o, instanceOf(C1.class, has(C2::bar, equalTo(2))));
    }
```

This needs to be considered carefully because it's not possible to achieve both, supporting `instanceOf` with raw types and type safe casting, at the same time.

### PR DESCRIPTION
**Pull request by dmfs**
This provides a Quality similar to `istanceOf` but also taking `Quality`s of subclasses of the given class. This is unsafe because there is no guarantee that the testee is actually of that subtype, but it may be required if the testee is a generic class.

It solves issues like described in
https://github.com/hamcrest/JavaHamcrest/issues/388

### CODE REVIEW

File: confidence-core/src/main/java/org/saynotobugs/confidence/quality/iterable/Iterates.java [hunk 1]
```diff
@@ -43,7 +43,7 @@
 
 
 @StaticFactories(value = "Core", packageName = "org.saynotobugs.confidence.quality")
-public final class Iterates<T> implements Quality<Iterable<T>>
+public final class Iterates<T> implements Quality<Iterable<? extends T>>
```
Comment (dmfs) [inline confidence-core/src/main/java/org/saynotobugs/confidence/quality/iterable/Iterates.java:46]: ups, this should be reverted

**Review by saynotobugsorg — APPROVED** [review]
